# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15RGKVgJXCnx2ucTqegGgDXKIkqjvlVUv
"""

import numpy as np #uses necesery libaries
import pandas as pd #uses necesery libaries
from mlxtend.frequent_patterns import apriori, association_rules # importing the apriori association rules

# Loading the dataset

data = pd.read_excel('Online Retail.xlsx')

# Showing the data

data.head()

# The columns in the data

data.columns

# The of the data

data.shape #we check the number of rows and columns

# Checkign whether there is any null values of not

data.isnull().values.any()

# As the previous cell told us that there are some null values. So, let's find them!

data.isnull().sum()

"""**Data Preprocessing**"""

# Stripping extra spaces in the description 
data['Description'] = data['Description'].str.strip() 
  
# Dropping the rows without any invoice number 
data.dropna(axis = 0, subset =['InvoiceNo'], inplace = True) 
data['InvoiceNo'] = data['InvoiceNo'].astype('str') 
  
# Dropping all transactions which were done on credit 
data = data[~data['InvoiceNo'].str.contains('C')]

# Let's see the countries in our dataset

data.Country.unique() #we check which countries are in the dayaset

# Splitting the data according to the region of transaction
# Transactions done in France 
basket_France = (data[data['Country'] =="France"] 
          .groupby(['InvoiceNo', 'Description'])['Quantity'] 
          .sum().unstack().reset_index().fillna(0) 
          .set_index('InvoiceNo'))

# Defining the hot encoding function to make the data suitable  

def hot_encode(x): #hot_encode defines essentially the representation of categorical variables as binary vectors
    if(x<= 0): 
        return 0
    if(x>= 1): 
        return 1

# Applying one hot encoding 

basket_encoded = basket_France.applymap(hot_encode) 
basket_France = basket_encoded

basket_France.head()

# Building the model 
frq_items = apriori(basket_France, min_support = 0.1, use_colnames = True) #for frnace country only , minimum support 0.1
  
# Collecting the inferred rules in a dataframe 
rules = association_rules(frq_items, metric ="lift", min_threshold = 1) #association_rules is a function
rules = rules.sort_values(['confidence', 'lift'], ascending =[False, False]) #sorting them according their confidence & lift value

print(rules.head()) #printing the rules

"""From the above output, it can be seen that paper cups and plates are bought together in France. This is because the French have a culture of having a get-together with their friends and family atleast once a week."""